stages:
  - build
  - test
  - release


test-robotools-py37:
  stage: test
  image: python:3.7
  script:
    - pip install pytest pytest-cov
    - pip install -e .
    - pytest --cov=./robotools --cov-report term-missing tests/tests.py

release-robotools:
  stage: release
  image: python:3.7
  script:
    - python setup.py bdist_wheel && cp dist/*.whl .
  artifacts:
    paths:
      - ./*.whl
    expire_in: 30 yrs
  only:
    # only run on refs that are named like v1.2 or v1.2.3
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
