name: pipeline

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --statistics
    - name: Test with pytest
      run: |
        pytest --cov=./robotools --cov-report xml --cov-report term-missing robotools
    - name: Upload coverage
      uses: codecov/codecov-action@v4.4.1
      with:
        file: ./coverage.xml
    - name: Test Wheel install and import
      run: |
        python setup.py bdist_wheel
        cd dist
        pip install robotools*.whl
        python -c "import robotools; print(robotools.__version__)"
    - name: Test Wheel with twine
      run: |
        twine check dist/*
